version: '3'
services:
  mongo:
    ports:
      - 27017:27017
  api-avaliacao:
    environment:
      NODE_ENV: dev
    command: bash -c "cd /api-avaliacao && npm i && npm i nodemon -g && npm run dev"